"use client";

import { useEffect } from "react";
import { Toaster, toast } from "@/components/ui/sonner";

const communityActivities = [
  "Laila registered with OmniBot.",
  "Arben completed a withdrawal with OmniBot.",
  "Amel connected a wallet to OmniBot.",
  "Marc created an OmniBot account.",
  "Ana explored the trading bot workspace.",
  "Jamal added an asset to their watchlist.",
  "Sofía connected a Phantom wallet.",
  "Arman reviewed their portfolio.",
  "Charlotte explored the rewards program.",
  "Lukas started setting up a trading bot.",
  "Leyla checked the latest market prices.",
  "Dwayne updated their account profile.",
  "Fatima explored newly listed assets.",
  "Rahim reviewed their wallet activity.",
  "Aaliyah completed a wallet deposit.",
  "Mikhail customized their watchlist.",
  "Emma explored automation settings.",
  "Daniel reviewed a trading strategy.",
  "Aïcha checked their portfolio performance.",
  "Tashi updated their notification preferences.",
  "Valentina explored the trading workspace guide.",
  "Amir reviewed their account settings.",
  "Naledi checked the activity dashboard.",
  "Gabriel started their automation journey.",
  "Nurul registered with OmniBot.",
  "Ivan completed a withdrawal with OmniBot.",
  "Aminata connected a wallet to OmniBot.",
  "Jean created an OmniBot account.",
  "Maria explored the trading bot workspace.",
  "Sokha added an asset to their watchlist.",
  "Béatrice connected a Phantom wallet.",
  "Liam reviewed their portfolio.",
  "Grâce explored the rewards program.",
  "Mahamat started setting up a trading bot.",
  "Isidora checked the latest market prices.",
  "Wei updated their account profile.",
  "Camila explored newly listed assets.",
  "Ahmed reviewed their wallet activity.",
  "Chantal completed a wallet deposit.",
  "Thierry customized their watchlist.",
  "María José explored automation settings.",
  "Koffi reviewed a trading strategy.",
  "Ivana checked their portfolio performance.",
  "Alejandro updated their notification preferences.",
  "Eleni explored the trading workspace guide.",
  "Jan reviewed their account settings.",
  "Freja checked the activity dashboard.",
  "Youssouf started their automation journey.",
  "Janelle registered with OmniBot.",
  "José completed a withdrawal with OmniBot.",
  "Daniela connected a wallet to OmniBot.",
  "Omar created an OmniBot account.",
  "Gabriela explored the trading bot workspace.",
  "Miguel added an asset to their watchlist.",
  "Selam connected a Phantom wallet.",
  "Tarmo reviewed their portfolio.",
  "Thandeka explored the rewards program.",
  "Dawit started setting up a trading bot.",
  "Litia checked the latest market prices.",
  "Mikko updated their account profile.",
  "Élodie explored newly listed assets.",
  "Olivier reviewed their wallet activity.",
  "Fatou completed a wallet deposit.",
  "Giorgi customized their watchlist.",
  "Hannah explored automation settings.",
  "Kwame reviewed a trading strategy.",
  "Andre checked their portfolio performance.",
  "Ximena updated their notification preferences.",
  "Mamadou explored the trading workspace guide.",
  "Binta reviewed their account settings.",
  "Ravi checked the activity dashboard.",
  "Nadège started their automation journey.",
  "Carlos registered with OmniBot.",
  "Eszter completed a withdrawal with OmniBot.",
  "Jón connected a wallet to OmniBot.",
  "Priya created an OmniBot account.",
  "Budi explored the trading bot workspace.",
  "Neda added an asset to their watchlist.",
  "Ali connected a Phantom wallet.",
  "Aoife reviewed their portfolio.",
  "Noam explored the rewards program.",
  "Giulia started setting up a trading bot.",
  "Yui checked the latest market prices.",
  "Aigerim updated their account profile.",
  "Kamau explored newly listed assets.",
  "Teata reviewed their wallet activity.",
  "Chol completed a wallet deposit.",
  "Seo-yeon customized their watchlist.",
  "Fahad explored automation settings.",
  "Aizada reviewed a trading strategy.",
  "Kham checked their portfolio performance.",
  "Līga updated their notification preferences.",
  "Karim explored the trading workspace guide.",
  "Nthabiseng reviewed their account settings.",
  "Emmanuel checked the activity dashboard.",
  "Aisha started their automation journey.",
  "Felix registered with OmniBot.",
  "Gabija completed a withdrawal with OmniBot.",
  "Luc connected a wallet to OmniBot.",
  "Fara created an OmniBot account.",
  "Chikondi explored the trading bot workspace.",
  "Aisyah added an asset to their watchlist.",
  "Hassan connected a Phantom wallet.",
  "Joseph reviewed their portfolio.",
  "Lina explored the rewards program.",
  "Mohamed started setting up a trading bot.",
  "Anjali checked the latest market prices.",
  "Santiago updated their account profile.",
  "Andrei explored newly listed assets.",
  "Camille reviewed their wallet activity.",
  "Bat-Erdene completed a wallet deposit.",
  "Milica customized their watchlist.",
  "Youssef explored automation settings.",
  "Amélia reviewed a trading strategy.",
  "Aung checked their portfolio performance.",
  "Ndapewa updated their notification preferences.",
  "David explored the trading workspace guide.",
  "Sita reviewed their account settings.",
  "Daan checked the activity dashboard.",
  "Maia started their automation journey.",
  "Aïssata registered with OmniBot.",
  "Chinedu completed a withdrawal with OmniBot.",
  "Elena connected a wallet to OmniBot.",
  "Lars created an OmniBot account.",
  "Alya explored the trading bot workspace.",
  "Hamza added an asset to their watchlist.",
  "Yousef connected a Phantom wallet.",
  "María reviewed their portfolio.",
  "Michael explored the rewards program.",
  "Rocío started setting up a trading bot.",
  "Diego checked the latest market prices.",
  "Angelica updated their account profile.",
  "Jakub explored newly listed assets.",
  "Inês reviewed their wallet activity.",
  "Khalid completed a wallet deposit.",
  "Andreea customized their watchlist.",
  "Dmitri explored automation settings.",
  "Aline reviewed a trading strategy.",
  "Shanice checked their portfolio performance.",
  "Sina updated their notification preferences.",
  "Luca explored the trading workspace guide.",
  "Esperança reviewed their account settings.",
  "Abdullah checked the activity dashboard.",
  "Awa started their automation journey.",
  "Nikola registered with OmniBot.",
  "Marie completed a withdrawal with OmniBot.",
  "Ibrahim connected a wallet to OmniBot.",
  "Mei Ling created an OmniBot account.",
  "Martin explored the trading bot workspace.",
  "Nika added an asset to their watchlist.",
  "Peter connected a Phantom wallet.",
  "Hodan reviewed their portfolio.",
  "Thabo explored the rewards program.",
  "Nyandeng started setting up a trading bot.",
  "Asha checked the latest market prices.",
  "Erik updated their account profile.",
  "Léa explored newly listed assets.",
  "Khaled reviewed their wallet activity.",
  "Zarina completed a wallet deposit.",
  "Juma customized their watchlist.",
  "Siriporn explored automation settings.",
  "Akossiwa reviewed a trading strategy.",
  "Sione checked their portfolio performance.",
  "Anisa updated their notification preferences.",
  "Yassine explored the trading workspace guide.",
  "Elif reviewed their account settings.",
  "Myrat checked the activity dashboard.",
  "Moses started their automation journey.",
  "Oksana registered with OmniBot.",
  "Saeed completed a withdrawal with OmniBot.",
  "Olivia connected a wallet to OmniBot.",
  "James created an OmniBot account.",
  "Lucía explored the trading bot workspace.",
  "Aziz added an asset to their watchlist.",
  "Mary connected a Phantom wallet.",
  "Giovanni reviewed their portfolio.",
  "Valeria explored the rewards program.",
  "Minh started setting up a trading bot.",
  "Amina checked the latest market prices.",
  "Chanda updated their account profile.",
  "Tariro explored newly listed assets.",
];

/** Preview notifications until a verified, consented activity feed is connected. */
export function CommunityActivity() {
  useEffect(() => {
    let timer: ReturnType<typeof setTimeout>;
    const remainingActivities = [...communityActivities];
    let toastId: string | number | undefined;

    function schedule(delay = 10_000) {
      if (remainingActivities.length === 0) return;

      timer = setTimeout(() => {
        if (document.visibilityState === "visible") {
          const index = Math.floor(Math.random() * remainingActivities.length);
          const [activity] = remainingActivities.splice(index, 1);
          toastId = toast("Activity Notification", {
            description: activity,
            toasterId: "community-activity",
            duration: 4000,
          });
        }
        schedule();
      }, delay);
    }

    schedule();
    return () => {
      clearTimeout(timer);
      if (toastId !== undefined) toast.dismiss(toastId);
    };
  }, []);

  return (
    <Toaster id="community-activity" position="bottom-left" visibleToasts={1} />
  );
}
