"use client";

import { Dialog } from "@base-ui/react/dialog";
import { ArrowDownToLine, Copy, X } from "lucide-react";
import { usePhantomAddress } from "@/lib/wallet/phantom";
import { PhantomConnect } from "@/components/wallet/phantom-connect";
import { toast } from "@/components/ui/sonner";

export function DepositButton({ className }: { className?: string }) {
  const address = usePhantomAddress();
  return <Dialog.Root><Dialog.Trigger className={className}><ArrowDownToLine className="size-5" />Deposit</Dialog.Trigger><Dialog.Portal><Dialog.Backdrop className="fixed inset-0 z-50 bg-slate-950/40 backdrop-blur-sm" /><Dialog.Popup data-dashboard className="fixed left-1/2 top-1/2 z-50 max-h-[90dvh] w-[calc(100%-32px)] max-w-md -translate-x-1/2 -translate-y-1/2 overflow-y-auto rounded-3xl bg-white p-6 text-neutral-900 shadow-2xl outline-none"><div className="flex items-center justify-between"><Dialog.Title className="text-xl font-semibold">Deposit to wallet</Dialog.Title><Dialog.Close aria-label="Close deposit" className="grid size-10 place-items-center rounded-full hover:bg-neutral-100"><X className="size-5" /></Dialog.Close></div><Dialog.Description className="mt-3 text-sm leading-6 text-neutral-500">Receive funds in your connected Phantom wallet.</Dialog.Description>{address ? <><label className="mt-5 block text-sm font-medium">Deposit account<select className="mt-2 min-h-12 w-full rounded-xl border border-neutral-200 bg-white px-3"><option>Phantom · {address.slice(0,4)}…{address.slice(-4)}</option></select></label><div className="my-5 rounded-2xl bg-blue-50 p-5"><p className="text-xs font-semibold uppercase tracking-wide text-blue-600">Solana network · SOL</p><p className="mt-3 break-all font-mono text-sm text-blue-950">{address}</p><button onClick={async () => { try { await navigator.clipboard.writeText(address);toast.success("Wallet address copied"); } catch { toast.error("Could not copy. Select and copy the address above."); } }} className="mt-4 inline-flex min-h-10 items-center gap-2 text-sm font-semibold text-blue-700"><Copy className="size-4" />Copy address</button></div><p className="text-sm leading-6 text-neutral-500">Send SOL on the Solana network to this address. Funds stay in your Phantom wallet and appear in your portfolio after network confirmation. Balances refresh every 30 seconds.</p></> : <div className="my-6"><PhantomConnect /></div>}<Dialog.Close className="mt-6 min-h-11 w-full rounded-xl bg-blue-600 text-sm font-semibold text-white">Done</Dialog.Close></Dialog.Popup></Dialog.Portal></Dialog.Root>;
}
